---
- name: Setup Nginx Web Server
  hosts: servers
  become: true
  tasks:

    - name: Update package lists
      apt:
        update_cache: yes
        cache_valid_time: 3600  # Cache valid for 1 hour

    - name: Install Nginx package
      apt:
        name: nginx
        state: present

    - name: Ensure Nginx service is enabled and running
      service:
        name: nginx
        state: started
        enabled: yes

    - name: Deploy custom index.html file
      copy:
        src: files/custom_index.html  # html code for this file and instructions in comments.md , do checkout 
        dest: /var/www/html/index.html
        owner: www-data
        group: www-data
        mode: '0644'

    - name: Open port 80 in the firewall
      ufw:
        rule: allow
        name: 'Nginx HTTP'

    - name: Verify Nginx service is running and accessible
      uri:
        url: http://localhost
        status_code: 200

