---
- name: Check Server Uptime and Update File
  hosts: servers
  gather_facts: no
  become: yes

  tasks:
    - name: Run uptime command
      command: uptime
      register: uptime_output

    - name: Display uptime result
      debug:
        msg: "System uptime: {{ uptime_output.stdout }}"

    - name: Ensure the /home/cselab3/ directory exists
      file:
        path: /home/cselab3/
        state: directory
        owner: cselab3
        mode: '0755'

    - name: Create sample_file.txt with correct ownership and permissions
      file:
        path: /home/cselab3/sample_file.txt
        state: touch
        owner: cselab3
        mode: '0644'

    - name: Write uptime information into the file
      copy:
        dest: /home/cselab3/sample_file.txt
        content: "Hello, this is a test file created by Ansible.\nSystem Uptime: {{ uptime_output.stdout }}"

        owner: cselab3
        mode: '0644'

    - name: Confirm file update
      debug:
        msg: "File updated successfully with uptime info: /home/cselab3/sample_file.txt"

